# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /work

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /work

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /work/CMakeFiles /work/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /work/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine.exe

# Build rule for target.
engine.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine.exe
.PHONY : engine.exe

# fast build rule for target.
engine.exe/fast:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/build
.PHONY : engine.exe/fast

#=============================================================================
# Target rules for targets named ace

# Build rule for target.
ace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ace
.PHONY : ace

# fast build rule for target.
ace/fast:
	$(MAKE) -f ace/CMakeFiles/ace.dir/build.make ace/CMakeFiles/ace.dir/build
.PHONY : ace/fast

src/bitmap_filters.obj: src/bitmap_filters.c.obj

.PHONY : src/bitmap_filters.obj

# target to build an object file
src/bitmap_filters.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/bitmap_filters.c.obj
.PHONY : src/bitmap_filters.c.obj

src/bitmap_filters.i: src/bitmap_filters.c.i

.PHONY : src/bitmap_filters.i

# target to preprocess a source file
src/bitmap_filters.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/bitmap_filters.c.i
.PHONY : src/bitmap_filters.c.i

src/bitmap_filters.s: src/bitmap_filters.c.s

.PHONY : src/bitmap_filters.s

# target to generate assembly for a file
src/bitmap_filters.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/bitmap_filters.c.s
.PHONY : src/bitmap_filters.c.s

src/dithering.obj: src/dithering.c.obj

.PHONY : src/dithering.obj

# target to build an object file
src/dithering.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/dithering.c.obj
.PHONY : src/dithering.c.obj

src/dithering.i: src/dithering.c.i

.PHONY : src/dithering.i

# target to preprocess a source file
src/dithering.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/dithering.c.i
.PHONY : src/dithering.c.i

src/dithering.s: src/dithering.c.s

.PHONY : src/dithering.s

# target to generate assembly for a file
src/dithering.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/dithering.c.s
.PHONY : src/dithering.c.s

src/draw_maps.obj: src/draw_maps.c.obj

.PHONY : src/draw_maps.obj

# target to build an object file
src/draw_maps.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_maps.c.obj
.PHONY : src/draw_maps.c.obj

src/draw_maps.i: src/draw_maps.c.i

.PHONY : src/draw_maps.i

# target to preprocess a source file
src/draw_maps.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_maps.c.i
.PHONY : src/draw_maps.c.i

src/draw_maps.s: src/draw_maps.c.s

.PHONY : src/draw_maps.s

# target to generate assembly for a file
src/draw_maps.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_maps.c.s
.PHONY : src/draw_maps.c.s

src/draw_screen.obj: src/draw_screen.c.obj

.PHONY : src/draw_screen.obj

# target to build an object file
src/draw_screen.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_screen.c.obj
.PHONY : src/draw_screen.c.obj

src/draw_screen.i: src/draw_screen.c.i

.PHONY : src/draw_screen.i

# target to preprocess a source file
src/draw_screen.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_screen.c.i
.PHONY : src/draw_screen.c.i

src/draw_screen.s: src/draw_screen.c.s

.PHONY : src/draw_screen.s

# target to generate assembly for a file
src/draw_screen.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_screen.c.s
.PHONY : src/draw_screen.c.s

src/draw_ships.obj: src/draw_ships.c.obj

.PHONY : src/draw_ships.obj

# target to build an object file
src/draw_ships.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_ships.c.obj
.PHONY : src/draw_ships.c.obj

src/draw_ships.i: src/draw_ships.c.i

.PHONY : src/draw_ships.i

# target to preprocess a source file
src/draw_ships.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_ships.c.i
.PHONY : src/draw_ships.c.i

src/draw_ships.s: src/draw_ships.c.s

.PHONY : src/draw_ships.s

# target to generate assembly for a file
src/draw_ships.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/draw_ships.c.s
.PHONY : src/draw_ships.c.s

src/file_read.obj: src/file_read.c.obj

.PHONY : src/file_read.obj

# target to build an object file
src/file_read.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/file_read.c.obj
.PHONY : src/file_read.c.obj

src/file_read.i: src/file_read.c.i

.PHONY : src/file_read.i

# target to preprocess a source file
src/file_read.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/file_read.c.i
.PHONY : src/file_read.c.i

src/file_read.s: src/file_read.c.s

.PHONY : src/file_read.s

# target to generate assembly for a file
src/file_read.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/file_read.c.s
.PHONY : src/file_read.c.s

src/main.obj: src/main.c.obj

.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/main.c.s
.PHONY : src/main.c.s

src/mipmaps.obj: src/mipmaps.c.obj

.PHONY : src/mipmaps.obj

# target to build an object file
src/mipmaps.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/mipmaps.c.obj
.PHONY : src/mipmaps.c.obj

src/mipmaps.i: src/mipmaps.c.i

.PHONY : src/mipmaps.i

# target to preprocess a source file
src/mipmaps.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/mipmaps.c.i
.PHONY : src/mipmaps.c.i

src/mipmaps.s: src/mipmaps.c.s

.PHONY : src/mipmaps.s

# target to generate assembly for a file
src/mipmaps.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/mipmaps.c.s
.PHONY : src/mipmaps.c.s

src/ray_casting.obj: src/ray_casting.c.obj

.PHONY : src/ray_casting.obj

# target to build an object file
src/ray_casting.c.obj:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/ray_casting.c.obj
.PHONY : src/ray_casting.c.obj

src/ray_casting.i: src/ray_casting.c.i

.PHONY : src/ray_casting.i

# target to preprocess a source file
src/ray_casting.c.i:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/ray_casting.c.i
.PHONY : src/ray_casting.c.i

src/ray_casting.s: src/ray_casting.c.s

.PHONY : src/ray_casting.s

# target to generate assembly for a file
src/ray_casting.c.s:
	$(MAKE) -f CMakeFiles/engine.exe.dir/build.make CMakeFiles/engine.exe.dir/src/ray_casting.c.s
.PHONY : src/ray_casting.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... engine.exe"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... ace"
	@echo "... src/bitmap_filters.obj"
	@echo "... src/bitmap_filters.i"
	@echo "... src/bitmap_filters.s"
	@echo "... src/dithering.obj"
	@echo "... src/dithering.i"
	@echo "... src/dithering.s"
	@echo "... src/draw_maps.obj"
	@echo "... src/draw_maps.i"
	@echo "... src/draw_maps.s"
	@echo "... src/draw_screen.obj"
	@echo "... src/draw_screen.i"
	@echo "... src/draw_screen.s"
	@echo "... src/draw_ships.obj"
	@echo "... src/draw_ships.i"
	@echo "... src/draw_ships.s"
	@echo "... src/file_read.obj"
	@echo "... src/file_read.i"
	@echo "... src/file_read.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mipmaps.obj"
	@echo "... src/mipmaps.i"
	@echo "... src/mipmaps.s"
	@echo "... src/ray_casting.obj"
	@echo "... src/ray_casting.i"
	@echo "... src/ray_casting.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

