#pragma once

#include "engine.h"

#define TERRAINDEPTH 64

#define XTURNBUFFOR 55


#define XSIZEODD 120 + XTURNBUFFOR * 2
#define XSIZEEVEN 80 + XTURNBUFFOR * 2

#define YSIZEODD 90
#define YSIZEEVEN YSIZEODD / 2

WORD rayCastXOdd[XSIZEODD][TERRAINDEPTH]; //51k
WORD rayCastYOdd[YSIZEODD][TERRAINDEPTH]; //51k

WORD rayCastXEven[XSIZEEVEN][TERRAINDEPTH]; //21k
WORD rayCastYEven[YSIZEEVEN][TERRAINDEPTH]; //21k

UBYTE renderingDepth = TERRAINDEPTH;

//AMIGA
UWORD plane1W[PLANEWIDTHWORD * PLANEHEIGHT]; //10k
UWORD plane2W[PLANEWIDTHWORD * PLANEHEIGHT]; //10k
UWORD plane3W[PLANEWIDTHWORD * PLANEHEIGHT]; //10k
UWORD plane4W[PLANEWIDTHWORD * PLANEHEIGHT]; //10k